# -*- coding: utf-8 -*-
"""Colab'e hoş geldiniz.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('global-data-on-sustainable-energy.csv')
df.head(5)

df.isnull().sum()

missing_counts =df.isnull().sum()
columns_to_drop = missing_counts[missing_counts > 1000].index.tolist()

df_clean = df.drop(columns=columns_to_drop)

df_subset = df[['Entity', 'Year', 'Renewable energy share in the total final energy consumption (%)']]
g7 = ['United States', 'United Kingdom', 'Germany', 'France', 'Italy', 'Canada', 'Japan']
brics = ['Brazil', 'Russia', 'India', 'China', 'South Africa']
target_countries = g7 + brics

df_subset = df_subset[df_subset['Entity'].isin(target_countries)]

numeric_cols = df_clean.select_dtypes(include='number').columns.tolist()

for col in numeric_cols:
  df_clean[col] = df_clean.groupby('Entity')[col].transform(lambda x: x.fillna(x.mean()))

df_clean=df_clean.dropna()

print(df_clean.shape)
print(df.isnull().sum().sum())

def assign_group(country):
    if country in g7:
        return 'G7'
    elif country in brics:
        return 'BRICS'
    else:
        return 'Other'

df_subset['Group'] = df_subset['Entity'].apply(assign_group)

df_subset = df_subset.dropna()

avg_renewable = df_clean.groupby(['Year', 'Group'])[
    'Renewable energy share in the total final energy consumption (%)'
].mean().reset_index()

plt.figure(figsize=(10,6))
sns.lineplot(data=avg_renewable,
             x='Year',
             y='Renewable energy share in the total final energy consumption (%)',
             hue='Group',
             marker='o')

plt.title("G7 vs BRICS: Yenilenebilir Enerji Oranı Zaman Serisi (2000–2020)")
plt.ylabel("Yenilenebilir Enerji Oranı (%)")
plt.xlabel("Yıl")
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))
sns.boxplot(data=df_subset,
            x='Group',
            y='Renewable energy share in the total final energy consumption (%)',
            palette='pastel')

plt.title("G7 vs BRICS: Yenilenebilir Enerji Oranı Dağılımı (2000–2020)")
plt.xlabel("Ülke Grubu")
plt.ylabel("Yenilenebilir Enerji Oranı (%)")
plt.grid(True)
plt.tight_layout()
plt.show()

grouped_means = df_subset.groupby(['Group', 'Entity'])[
    'Renewable energy share in the total final energy consumption (%)'
].mean().reset_index()

leaders = grouped_means.loc[grouped_means.groupby('Group')[
    'Renewable energy share in the total final energy consumption (%)'
].idxmax()]

print("Grup içi lider ülkeler: \n")
print(leaders)